ASPCore_Final/ASPCore_Final/Models/ForgetPassword.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPCore_Final.Models
{
    public class ForgetPassword
    {
        public string UserEmail { set; get; }
    }
}

ASPCore_Final/ASPCore_Final/Controllers/ForgetPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASPCore_Final.Models;
using System.Net.Mail;
using System.Text;

namespace ASPCore_Final.Controllers
{
    public class ForgetPasswordController : Controller
    {
        private readonly ESHOPContext db;
        public ForgetPasswordController(ESHOPContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public string CreatePassword(int length)
        {
            const string valid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder res = new StringBuilder();
            Random rnd = new Random();
            while (0 < length--)
            {
                res.Append(valid[rnd.Next(valid.Length)]);
            }
            return res.ToString();
        }
        public IActionResult Forget(ForgetPassword model)
        {
            if (ModelState.IsValid)
            {
                KhachHang kh = db.KhachHang.SingleOrDefault(p => p.Email == model.UserEmail);
                if (kh == null)
                {
                    ModelState.AddModelError("Lỗi", "Email không tồn tại trong dữ liệu");
                    return View("Index");
                }
                else
                {
                    string mk = CreatePassword(12);
                    kh.MatKhau = Encryptor.MD5Hash(mk);
                    db.Update(kh);
                    db.SaveChangesAsync();
                    MailMessage mm = new MailMessage("eshoppingmanager@gmail.com", model.UserEmail);
                    mm.Subject = "Mật khẩu tài khoản Eshop";
                    mm.Body = string.Format("Xin chào: <h1>{0}</h1> <br/> Mật khẩu mới của bạn là <h1>{1}</h1>", kh.HoTen, mk);
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    smtp.Credentials = new System.Net.NetworkCredential("eshoppingmanager@gmail.com", "eshop147258369");
                    smtp.Send(mm);
                    TempData["Success"] = "Xin hãy kiểm tra Email của bạn!";
                    return View("Index");
                }
            }
            return View("Index");
        }
    }
}

ASPCore_Final/ASPCore_Final/Views/ForgetPassword/Index.cshtml
@model ASPCore_Final.Models.ForgetPassword
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_frontEnd.cshtml";
}
@section breadcumb{
    <div class="breadcrumbs">
        <div class="container">
            <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
                <li><a asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Trang chủ</a></li>
                <li class="active">Quên mật khẩu</li>
            </ol>
        </div>
    </div>
}
<div class="forgot">
    <div class="container">
        <div class="login-form-grids animated wow slideInUp" data-wow-delay=".5s">
            @if (TempData["Success"] != null)
            {
                <div class="text-success">
                    <p><strong>Thành công!</strong> @TempData["Success"].ToString()</p>
                </div>
            }
            <h3 class="animated wow zoomIn" style="text-align:center;">Nhập email tài khoản của bạn</h3>
            <form method="post" asp-controller="ForgetPassword" asp-action="Forget">
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <input asp-for="UserEmail" type="email" placeholder="Địa chỉ email" required>
                <input type="submit" value="Xác nhận">
            </form>
        </div>
    </div>
</div>