ASPCore_Final/ASPCore_Final/Models/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ASPCore_Final.Models
{
    public class ChangePassword
    {
        [Display(Name = "MK Mới")]
        public string MatKhauMoi { set; get; }
        [Display(Name = "Xác nhận MK")]
        public string XacNhanMatKhauMoi { set; get; }
    }
}

ASPCore_Final/ASPCore_Final/Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASPCore_Final.Models;

namespace ASPCore_Final.Controllers
{
    public class ChangePasswordController : Controller
    {
        private readonly ESHOPContext db;
        public ChangePasswordController(ESHOPContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Change(ChangePassword model)
        {
            if (ModelState.IsValid)
            {
                KhachHang kh = HttpContext.Session.Get<KhachHang>("user");
                if (model.MatKhauMoi != model.XacNhanMatKhauMoi)
                {
                    ModelState.AddModelError("Lỗi", "Mật khẩu xác nhận không khớp");
                    return View("Index");
                }
                else
                {
                    kh.MatKhau = Encryptor.MD5Hash(model.MatKhauMoi);
                    db.Update(kh);
                    db.SaveChangesAsync();
                    HttpContext.Session.Remove("user");
                    if (HttpContext.Session.Get<string>("mess") != null)
                        HttpContext.Session.Remove("mess");
                    return RedirectToAction("Index", "Login");
                }
            }
            return View("Index");
        }
    }
}

ASPCore_Final/ASPCore_Final/Views/ChangePassword/Index.cshtml
@model ASPCore_Final.Models.ChangePassword
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_frontEnd.cshtml";
}
@section breadcumb{
    <div class="breadcrumbs">
        <div class="container">
            <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
                <li><a asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Trang chủ</a></li>
                <li class="active">Đổi mật khẩu</li>
            </ol>
        </div>
    </div>
}
<div class="forgot">
    <div class="container">
        <div class="login-form-grids animated wow slideInUp" data-wow-delay=".5s">
            <h3 class="animated wow zoomIn" style="text-align:center;">Đổi mật khẩu</h3>
            <form method="post" asp-controller="ChangePassword" asp-action="Change">
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <input asp-for="MatKhauMoi" type="password" placeholder="Mật khẩu mới" required>
                <input asp-for="XacNhanMatKhauMoi" type="password" placeholder="Xác nhận mật khẩu mới" required>
                <input type="submit" value="Xác nhận">
            </form>
        </div>
    </div>
</div>